/**
 * Cloned WebApp API Services — Next.js & React Hooks SDK
 * Auto-generated by AGY Website Cloner Plugin
 */

'use client';

import { useState, useCallback, useEffect } from 'react';

export interface ScrapeOptions {
  url: string;
  formats?: ('markdown' | 'html' | 'rawHtml' | 'links' | 'screenshot')[];
  onlyMainContent?: boolean;
  waitFor?: number;
}

export interface CrawlOptions {
  url: string;
  limit?: number;
  maxDepth?: number;
}

export interface ExtractOptions {
  url: string;
  prompt?: string;
  schema: Record<string, any>;
}

export class FirecrawlAppClient {
  private baseUrl: string;
  private apiKey?: string;

  constructor(config: { baseUrl?: string; apiKey?: string } = {}) {
    this.baseUrl = (config.baseUrl || 'http://localhost:3000').replace(/\/$/, '');
    this.apiKey = config.apiKey;
  }

  private async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...(this.apiKey ? { Authorization: `Bearer ${this.apiKey}` } : {}),
      ...((options.headers as Record<string, string>) || {}),
    };

    const res = await fetch(`${this.baseUrl}${path}`, {
      ...options,
      headers,
    });

    if (!res.ok) {
      const errorJson = await res.json().catch(() => ({}));
      throw new Error(errorJson.error || `HTTP error ${res.status}: ${res.statusText}`);
    }

    return res.json() as Promise<T>;
  }

  async scrape(options: ScrapeOptions) {
    return this.request<{ success: boolean; data: any }>('/api/v1/scrape', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async crawl(options: CrawlOptions) {
    return this.request<{ success: boolean; id: string; status: string; total: number }>('/api/v1/crawl', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  keys = {
    list: async (workspaceId?: string) => {
      const qs = workspaceId ? `?workspaceId=${encodeURIComponent(workspaceId)}` : '';
      return this.request<{ success: boolean; keys: any[] }>(`/api/v1/keys${qs}`, {
        method: 'GET',
      });
    },
    create: async (name: string, workspaceId?: string) => {
      return this.request<{ success: boolean; key: any }>('/api/v1/keys', {
        method: 'POST',
        body: JSON.stringify({ name, workspaceId }),
      });
    },
    delete: async (id: string) => {
      return this.request<{ success: boolean; message: string }>(`/api/v1/keys?id=${encodeURIComponent(id)}`, {
        method: 'DELETE',
      });
    },
  };
}

const defaultClient = new FirecrawlAppClient();

export function useScrape(client: FirecrawlAppClient = defaultClient) {
  const [data, setData] = useState<any | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const execute = useCallback(async (options: ScrapeOptions) => {
    setLoading(true);
    setError(null);
    try {
      const res = await client.scrape(options);
      setData(res.data);
      return res.data;
    } catch (err: any) {
      setError(err.message || 'Scrape failed');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [client]);

  return { data, loading, error, scrape: execute };
}

export function useCrawlStream(baseUrl: string = 'http://localhost:3000') {
  const [progress, setProgress] = useState(0);
  const [logs, setLogs] = useState<string[]>([]);
  const [result, setResult] = useState<any | null>(null);
  const [isStreaming, setIsStreaming] = useState(false);

  const startStream = useCallback(async (url: string, limit: number = 5) => {
    setIsStreaming(true);
    setProgress(0);
    setLogs([]);
    setResult(null);

    const res = await fetch(`${baseUrl}/api/v1/crawl/stream?url=${encodeURIComponent(url)}&limit=${limit}`);
    if (!res.body) throw new Error('ReadableStream not supported');

    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { value, done } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n\n');
      buffer = lines.pop() || '';

      for (const chunk of lines) {
        const eventMatch = chunk.match(/event:\s*([^\n]+)/);
        const dataMatch = chunk.match(/data:\s*([^\n]+)/);

        if (eventMatch && dataMatch) {
          const eventType = eventMatch[1].trim();
          const eventData = JSON.parse(dataMatch[1]);

          if (eventType === 'progress') {
            setProgress(eventData.percent);
            setLogs((prev) => [...prev, `[${eventData.time}] ${eventData.log}`]);
          } else if (eventType === 'done') {
            setProgress(100);
            setResult(eventData);
          }
        }
      }
    }
    setIsStreaming(false);
  }, [baseUrl]);

  return { progress, logs, result, isStreaming, startStream };
}

export function useApiKeys(workspaceId?: string, client: FirecrawlAppClient = defaultClient) {
  const [keys, setKeys] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const res = await client.keys.list(workspaceId);
      setKeys(res.keys || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }, [workspaceId, client]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  const createKey = async (name: string) => {
    const res = await client.keys.create(name, workspaceId);
    setKeys((prev) => [...prev, res.key]);
    return res.key;
  };

  const deleteKey = async (id: string) => {
    await client.keys.delete(id);
    setKeys((prev) => prev.filter((k) => k.id !== id));
  };

  return { keys, loading, refresh, createKey, deleteKey };
}
