#!/usr/bin/env node

/**
 * generate-sdk.mjs — Multi-Language SDK Generator
 *
 * Automatically generates production-grade Client SDKs across 4 language/framework targets:
 * 1. Node.js & TypeScript (packages/sdk-node & src/sdk/client.ts)
 * 2. Next.js & React Hooks (packages/sdk-react & src/sdk/react.ts)
 * 3. C# / .NET 8+ (packages/sdk-csharp/FirecrawlClient.cs)
 * 4. Python 3.9+ (packages/sdk-py/firecrawl_client/client.py)
 *
 * Usage:
 *   node generate-sdk.mjs [--spec docs/api/openapi.json]
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

function parseArgs() {
  const args = process.argv.slice(2);
  let specPath = resolve(process.cwd(), 'docs', 'api', 'openapi.json');

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--spec' && args[i + 1]) {
      specPath = resolve(args[i + 1]);
      i++;
    }
  }

  return { specPath };
}

// 1. TypeScript & Node.js SDK
function generateNodeTsSdk(spec) {
  return `/**
 * ${spec.info.title} — Node.js & TypeScript Client SDK
 * Auto-generated by AGY Website Cloner Plugin
 * Version: ${spec.info.version}
 */

export interface ScrapeOptions {
  url: string;
  formats?: ('markdown' | 'html' | 'rawHtml' | 'links' | 'screenshot')[];
  onlyMainContent?: boolean;
  waitFor?: number;
}

export interface CrawlOptions {
  url: string;
  limit?: number;
  maxDepth?: number;
}

export interface MapOptions {
  url: string;
  search?: string;
  limit?: number;
}

export interface ExtractOptions {
  url: string;
  prompt?: string;
  schema: Record<string, any>;
}

export interface ContactOptions {
  name: string;
  email: string;
  subject?: string;
  message: string;
}

export class FirecrawlAppClient {
  private baseUrl: string;
  private apiKey?: string;

  constructor(config: { baseUrl?: string; apiKey?: string } = {}) {
    this.baseUrl = (config.baseUrl || 'http://localhost:3000').replace(/\\/$/, '');
    this.apiKey = config.apiKey;
  }

  private async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...(this.apiKey ? { Authorization: \`Bearer \${this.apiKey}\` } : {}),
      ...((options.headers as Record<string, string>) || {}),
    };

    const res = await fetch(\`\${this.baseUrl}\${path}\`, {
      ...options,
      headers,
    });

    if (!res.ok) {
      const errorJson = await res.json().catch(() => ({}));
      throw new Error(errorJson.error || \`HTTP error \${res.status}: \${res.statusText}\`);
    }

    return res.json() as Promise<T>;
  }

  // Core Scraping
  async scrape(options: ScrapeOptions) {
    return this.request<{ success: boolean; data: any }>('/api/v1/scrape', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async crawl(options: CrawlOptions) {
    return this.request<{ success: boolean; id: string; status: string; total: number }>('/api/v1/crawl', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async map(options: MapOptions) {
    return this.request<{ success: boolean; links: string[]; total: number }>('/api/v1/map', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async extract(options: ExtractOptions) {
    return this.request<{ success: boolean; data: any; metadata: any }>('/api/v1/extract', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  // Keys Management
  keys = {
    list: async (workspaceId?: string) => {
      const qs = workspaceId ? \`?workspaceId=\${encodeURIComponent(workspaceId)}\` : '';
      return this.request<{ success: boolean; keys: any[] }>(\`/api/v1/keys\${qs}\`, {
        method: 'GET',
      });
    },
    create: async (name: string, workspaceId?: string) => {
      return this.request<{ success: boolean; key: any }>('/api/v1/keys', {
        method: 'POST',
        body: JSON.stringify({ name, workspaceId }),
      });
    },
    delete: async (id: string) => {
      return this.request<{ success: boolean; message: string }>(\`/api/v1/keys?id=\${encodeURIComponent(id)}\`, {
        method: 'DELETE',
      });
    },
  };

  // Usage & Stats
  async getUsage(workspaceId?: string) {
    const qs = workspaceId ? \`?workspaceId=\${encodeURIComponent(workspaceId)}\` : '';
    return this.request<{
      success: boolean;
      creditsUsedThisMonth: number;
      creditsTotal: number;
      creditsRemaining: number;
      recentRequests: any[];
    }>(\`/api/v1/usage\${qs}\`, {
      method: 'GET',
    });
  }

  // Contact Inquiries
  async submitInquiry(options: ContactOptions) {
    return this.request<{ success: boolean; message: string; inquiryId: string }>('/api/v1/contact', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }
}
`;
}

// 2. Next.js & React Hooks SDK
function generateReactSdk(spec) {
  return `/**
 * ${spec.info.title} — Next.js & React Hooks SDK
 * Auto-generated by AGY Website Cloner Plugin
 */

'use client';

import { useState, useCallback, useEffect } from 'react';

export interface ScrapeOptions {
  url: string;
  formats?: ('markdown' | 'html' | 'rawHtml' | 'links' | 'screenshot')[];
  onlyMainContent?: boolean;
  waitFor?: number;
}

export interface CrawlOptions {
  url: string;
  limit?: number;
  maxDepth?: number;
}

export interface ExtractOptions {
  url: string;
  prompt?: string;
  schema: Record<string, any>;
}

export class FirecrawlAppClient {
  private baseUrl: string;
  private apiKey?: string;

  constructor(config: { baseUrl?: string; apiKey?: string } = {}) {
    this.baseUrl = (config.baseUrl || 'http://localhost:3000').replace(/\\/$/, '');
    this.apiKey = config.apiKey;
  }

  private async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...(this.apiKey ? { Authorization: \`Bearer \${this.apiKey}\` } : {}),
      ...((options.headers as Record<string, string>) || {}),
    };

    const res = await fetch(\`\${this.baseUrl}\${path}\`, {
      ...options,
      headers,
    });

    if (!res.ok) {
      const errorJson = await res.json().catch(() => ({}));
      throw new Error(errorJson.error || \`HTTP error \${res.status}: \${res.statusText}\`);
    }

    return res.json() as Promise<T>;
  }

  async scrape(options: ScrapeOptions) {
    return this.request<{ success: boolean; data: any }>('/api/v1/scrape', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async crawl(options: CrawlOptions) {
    return this.request<{ success: boolean; id: string; status: string; total: number }>('/api/v1/crawl', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  keys = {
    list: async (workspaceId?: string) => {
      const qs = workspaceId ? \`?workspaceId=\${encodeURIComponent(workspaceId)}\` : '';
      return this.request<{ success: boolean; keys: any[] }>(\`/api/v1/keys\${qs}\`, {
        method: 'GET',
      });
    },
    create: async (name: string, workspaceId?: string) => {
      return this.request<{ success: boolean; key: any }>('/api/v1/keys', {
        method: 'POST',
        body: JSON.stringify({ name, workspaceId }),
      });
    },
    delete: async (id: string) => {
      return this.request<{ success: boolean; message: string }>(\`/api/v1/keys?id=\${encodeURIComponent(id)}\`, {
        method: 'DELETE',
      });
    },
  };
}

const defaultClient = new FirecrawlAppClient();

export function useScrape(client: FirecrawlAppClient = defaultClient) {
  const [data, setData] = useState<any | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const execute = useCallback(async (options: ScrapeOptions) => {
    setLoading(true);
    setError(null);
    try {
      const res = await client.scrape(options);
      setData(res.data);
      return res.data;
    } catch (err: any) {
      setError(err.message || 'Scrape failed');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [client]);

  return { data, loading, error, scrape: execute };
}

export function useCrawlStream(baseUrl: string = 'http://localhost:3000') {
  const [progress, setProgress] = useState(0);
  const [logs, setLogs] = useState<string[]>([]);
  const [result, setResult] = useState<any | null>(null);
  const [isStreaming, setIsStreaming] = useState(false);

  const startStream = useCallback(async (url: string, limit: number = 5) => {
    setIsStreaming(true);
    setProgress(0);
    setLogs([]);
    setResult(null);

    const res = await fetch(\`\${baseUrl}/api/v1/crawl/stream?url=\${encodeURIComponent(url)}&limit=\${limit}\`);
    if (!res.body) throw new Error('ReadableStream not supported');

    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { value, done } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\\n\\n');
      buffer = lines.pop() || '';

      for (const chunk of lines) {
        const eventMatch = chunk.match(/event:\\s*([^\\n]+)/);
        const dataMatch = chunk.match(/data:\\s*([^\\n]+)/);

        if (eventMatch && dataMatch) {
          const eventType = eventMatch[1].trim();
          const eventData = JSON.parse(dataMatch[1]);

          if (eventType === 'progress') {
            setProgress(eventData.percent);
            setLogs((prev) => [...prev, \`[\${eventData.time}] \${eventData.log}\`]);
          } else if (eventType === 'done') {
            setProgress(100);
            setResult(eventData);
          }
        }
      }
    }
    setIsStreaming(false);
  }, [baseUrl]);

  return { progress, logs, result, isStreaming, startStream };
}

export function useApiKeys(workspaceId?: string, client: FirecrawlAppClient = defaultClient) {
  const [keys, setKeys] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const res = await client.keys.list(workspaceId);
      setKeys(res.keys || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }, [workspaceId, client]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  const createKey = async (name: string) => {
    const res = await client.keys.create(name, workspaceId);
    setKeys((prev) => [...prev, res.key]);
    return res.key;
  };

  const deleteKey = async (id: string) => {
    await client.keys.delete(id);
    setKeys((prev) => prev.filter((k) => k.id !== id));
  };

  return { keys, loading, refresh, createKey, deleteKey };
}
`;
}

// 3. C# / .NET SDK
function generateCSharpSdk(spec) {
  return `// <auto-generated>
// ${spec.info.title} — C# / .NET Client SDK
// Auto-generated by AGY Website Cloner Plugin
// Version: ${spec.info.version}
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Firecrawl.Client
{
    public class ScrapeOptions
    {
        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        [JsonPropertyName("formats")]
        public List<string>? Formats { get; set; } = new() { "markdown" };

        [JsonPropertyName("onlyMainContent")]
        public bool OnlyMainContent { get; set; } = true;

        [JsonPropertyName("waitFor")]
        public int WaitFor { get; set; } = 0;
    }

    public class CrawlOptions
    {
        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        [JsonPropertyName("limit")]
        public int Limit { get; set; } = 10;

        [JsonPropertyName("maxDepth")]
        public int MaxDepth { get; set; } = 2;
    }

    public class ExtractOptions
    {
        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        [JsonPropertyName("prompt")]
        public string? Prompt { get; set; }

        [JsonPropertyName("schema")]
        public Dictionary<string, object> Schema { get; set; } = new();
    }

    public class ContactOptions
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;

        [JsonPropertyName("email")]
        public string Email { get; set; } = string.Empty;

        [JsonPropertyName("subject")]
        public string? Subject { get; set; } = "Inquiry";

        [JsonPropertyName("message")]
        public string Message { get; set; } = string.Empty;
    }

    public class ApiResponse<T>
    {
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        [JsonPropertyName("data")]
        public T? Data { get; set; }

        [JsonPropertyName("error")]
        public string? Error { get; set; }
    }

    public class FirecrawlClient : IDisposable
    {
        private readonly HttpClient _httpClient;
        private readonly bool _disposeClient;

        public FirecrawlClient(string baseUrl = "http://localhost:3000", string? apiKey = null, HttpClient? httpClient = null)
        {
            _disposeClient = httpClient == null;
            _httpClient = httpClient ?? new HttpClient { BaseAddress = new Uri(baseUrl.TrimEnd('/')) };

            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            if (!string.IsNullOrEmpty(apiKey))
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
            }
        }

        private async Task<T> SendJsonAsync<T>(HttpMethod method, string path, object? body = null, CancellationToken cancellationToken = default)
        {
            using var request = new HttpRequestMessage(method, path);

            if (body != null)
            {
                var json = JsonSerializer.Serialize(body);
                request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            }

            using var response = await _httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);
            var content = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                throw new HttpRequestException($"API request failed with status {response.StatusCode}: {content}");
            }

            return JsonSerializer.Deserialize<T>(content, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;
        }

        public Task<ApiResponse<JsonElement>> ScrapeAsync(ScrapeOptions options, CancellationToken ct = default)
            => SendJsonAsync<ApiResponse<JsonElement>>(HttpMethod.Post, "/api/v1/scrape", options, ct);

        public Task<JsonElement> CrawlAsync(CrawlOptions options, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/crawl", options, ct);

        public Task<JsonElement> MapAsync(string url, int limit = 100, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/map", new { url, limit }, ct);

        public Task<JsonElement> ExtractAsync(ExtractOptions options, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/extract", options, ct);

        public Task<JsonElement> ListKeysAsync(string? workspaceId = null, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Get, $"/api/v1/keys{(workspaceId != null ? $"?workspaceId={workspaceId}" : "")}", null, ct);

        public Task<JsonElement> CreateKeyAsync(string name, string? workspaceId = null, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/keys", new { name, workspaceId }, ct);

        public Task<JsonElement> DeleteKeyAsync(string keyId, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Delete, $"/api/v1/keys?id={keyId}", null, ct);

        public Task<JsonElement> GetUsageAsync(string? workspaceId = null, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Get, $"/api/v1/usage{(workspaceId != null ? $"?workspaceId={workspaceId}" : "")}", null, ct);

        public Task<JsonElement> SubmitInquiryAsync(ContactOptions options, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/contact", options, ct);

        public void Dispose()
        {
            if (_disposeClient)
            {
                _httpClient.Dispose();
            }
        }
    }
}
`;
}

// 4. Python SDK
function generatePythonSdk(spec) {
  return `"""
${spec.info.title} — Python Client SDK
Auto-generated by AGY Website Cloner Plugin
Version: ${spec.info.version}
"""

import json
import urllib.request
import urllib.error
from typing import Dict, Any, List, Optional

class FirecrawlAppClient:
    def __init__(self, base_url: str = "http://localhost:3000", api_key: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key

    def _request(self, method: str, path: str, data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        url = f"{self.base_url}{path}"
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        body_bytes = json.dumps(data).encode("utf-8") if data else None
        req = urllib.request.Request(url, data=body_bytes, headers=headers, method=method)

        try:
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            error_text = e.read().decode("utf-8")
            raise RuntimeError(f"HTTP {e.code}: {error_text}")

    def scrape(self, url: str, formats: Optional[List[str]] = None, only_main_content: bool = True) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/scrape", {
            "url": url,
            "formats": formats or ["markdown"],
            "onlyMainContent": only_main_content,
        })

    def crawl(self, url: str, limit: int = 10, max_depth: int = 2) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/crawl", {
            "url": url,
            "limit": limit,
            "maxDepth": max_depth,
        })

    def map(self, url: str, search: Optional[str] = None, limit: int = 100) -> Dict[str, Any]:
        payload: Dict[str, Any] = {"url": url, "limit": limit}
        if search:
            payload["search"] = search
        return self._request("POST", "/api/v1/map", payload)

    def extract(self, url: str, schema: Dict[str, Any], prompt: Optional[str] = None) -> Dict[str, Any]:
        payload: Dict[str, Any] = {"url": url, "schema": schema}
        if prompt:
            payload["prompt"] = prompt
        return self._request("POST", "/api/v1/extract", payload)

    def list_keys(self, workspace_id: Optional[str] = None) -> Dict[str, Any]:
        qs = f"?workspaceId={workspace_id}" if workspace_id else ""
        return self._request("GET", f"/api/v1/keys{qs}")

    def create_key(self, name: str, workspace_id: Optional[str] = None) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/keys", {"name": name, "workspaceId": workspace_id})

    def delete_key(self, key_id: str) -> Dict[str, Any]:
        return self._request("DELETE", f"/api/v1/keys?id={key_id}")

    def get_usage(self, workspace_id: Optional[str] = None) -> Dict[str, Any]:
        qs = f"?workspaceId={workspace_id}" if workspace_id else ""
        return self._request("GET", f"/api/v1/usage{qs}")

    def submit_inquiry(self, name: str, email: str, message: str, subject: Optional[str] = None) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/contact", {
            "name": name,
            "email": email,
            "subject": subject or "Inquiry",
            "message": message,
        })
`;
}

function main() {
  const { specPath } = parseArgs();
  console.log(`[website-cloner:sdk] Generating Multi-Language SDKs from ${specPath}...\n`);

  const spec = JSON.parse(readFileSync(specPath, 'utf8'));

  // 1. Node.js & TypeScript SDK
  const nodeOutDir = resolve(process.cwd(), 'packages', 'sdk-node', 'src');
  const appTsSdk = resolve(process.cwd(), 'src', 'sdk');
  mkdirSync(nodeOutDir, { recursive: true });
  mkdirSync(appTsSdk, { recursive: true });

  const nodeTsCode = generateNodeTsSdk(spec);
  writeFileSync(resolve(nodeOutDir, 'index.ts'), nodeTsCode, 'utf8');
  writeFileSync(resolve(appTsSdk, 'client.ts'), nodeTsCode, 'utf8');

  const nodePkgJson = {
    name: '@cloner/node-sdk',
    version: '1.0.0',
    description: 'Node.js & TypeScript Client SDK for Cloned WebApp APIs',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: { build: 'tsc' },
    keywords: ['sdk', 'firecrawl', 'node', 'typescript'],
  };
  writeFileSync(resolve(process.cwd(), 'packages', 'sdk-node', 'package.json'), JSON.stringify(nodePkgJson, null, 2), 'utf8');
  console.log(`  ✓ 1. Node.js & TypeScript SDK -> packages/sdk-node/ & src/sdk/client.ts`);

  // 2. Next.js & React Hooks SDK
  const reactOutDir = resolve(process.cwd(), 'packages', 'sdk-react', 'src');
  mkdirSync(reactOutDir, { recursive: true });
  const reactCode = generateReactSdk(spec);
  writeFileSync(resolve(reactOutDir, 'index.ts'), reactCode, 'utf8');
  writeFileSync(resolve(appTsSdk, 'react.ts'), reactCode, 'utf8');

  const reactPkgJson = {
    name: '@cloner/react-sdk',
    version: '1.0.0',
    description: 'Next.js & React Hooks Client SDK for Cloned WebApp APIs',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    peerDependencies: { react: '^18.0.0 || ^19.0.0' },
    keywords: ['react', 'nextjs', 'hooks', 'sdk'],
  };
  writeFileSync(resolve(process.cwd(), 'packages', 'sdk-react', 'package.json'), JSON.stringify(reactPkgJson, null, 2), 'utf8');
  console.log(`  ✓ 2. Next.js & React Hooks SDK -> packages/sdk-react/ & src/sdk/react.ts`);

  // 3. C# / .NET SDK
  const csharpOutDir = resolve(process.cwd(), 'packages', 'sdk-csharp');
  mkdirSync(csharpOutDir, { recursive: true });
  const csharpCode = generateCSharpSdk(spec);
  writeFileSync(resolve(csharpOutDir, 'FirecrawlClient.cs'), csharpCode, 'utf8');

  const csprojContent = `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Firecrawl.Client</PackageId>
    <Version>1.0.0</Version>
    <Authors>Website Cloner Plugin</Authors>
    <Description>C# / .NET Client SDK for Cloned WebApp APIs</Description>
    <PackageTags>firecrawl;scraping;crawler;sdk;csharp</PackageTags>
  </PropertyGroup>
</Project>`;
  writeFileSync(resolve(csharpOutDir, 'FirecrawlClient.csproj'), csprojContent, 'utf8');
  console.log(`  ✓ 3. C# / .NET 8+ SDK -> packages/sdk-csharp/FirecrawlClient.cs & .csproj`);

  // 4. Python SDK
  const pyOutDir = resolve(process.cwd(), 'packages', 'sdk-py', 'firecrawl_client');
  mkdirSync(pyOutDir, { recursive: true });
  const pyCode = generatePythonSdk(spec);
  writeFileSync(resolve(pyOutDir, '__init__.py'), 'from .client import FirecrawlAppClient\n', 'utf8');
  writeFileSync(resolve(pyOutDir, 'client.py'), pyCode, 'utf8');

  const pyProjectToml = `[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "firecrawl-app-client"
version = "1.0.0"
description = "Python Client SDK for Cloned WebApp APIs"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["firecrawl", "scraper", "crawler", "sdk"]
`;
  writeFileSync(resolve(process.cwd(), 'packages', 'sdk-py', 'pyproject.toml'), pyProjectToml, 'utf8');
  console.log(`  ✓ 4. Python 3.9+ SDK -> packages/sdk-py/firecrawl_client/client.py & pyproject.toml`);

  console.log(`\n🎉 All 4 Client SDKs successfully generated!`);
}

main();
