/**
 * Cloned WebApp API Services — TypeScript Client SDK
 * Auto-generated by AGY Website Cloner Plugin
 * Version: 1.0.0
 */

export interface ScrapeOptions {
  url: string;
  formats?: ('markdown' | 'html' | 'rawHtml' | 'links' | 'screenshot')[];
  onlyMainContent?: boolean;
  waitFor?: number;
}

export interface CrawlOptions {
  url: string;
  limit?: number;
  maxDepth?: number;
}

export interface MapOptions {
  url: string;
  search?: string;
  limit?: number;
}

export interface ExtractOptions {
  url: string;
  prompt?: string;
  schema: Record<string, any>;
}

export interface ContactOptions {
  name: string;
  email: string;
  subject?: string;
  message: string;
}

export class FirecrawlAppClient {
  private baseUrl: string;
  private apiKey?: string;

  constructor(config: { baseUrl?: string; apiKey?: string } = {}) {
    this.baseUrl = config.baseUrl || 'http://localhost:3000';
    this.apiKey = config.apiKey;
  }

  private async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...(this.apiKey ? { Authorization: `Bearer ${this.apiKey}` } : {}),
      ...((options.headers as Record<string, string>) || {}),
    };

    const res = await fetch(`${this.baseUrl}${path}`, {
      ...options,
      headers,
    });

    if (!res.ok) {
      const errorJson = await res.json().catch(() => ({}));
      throw new Error(errorJson.error || `HTTP error ${res.status}: ${res.statusText}`);
    }

    return res.json() as Promise<T>;
  }

  // Core Scraping
  async scrape(options: ScrapeOptions) {
    return this.request<{ success: boolean; data: any }>('/api/v1/scrape', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async crawl(options: CrawlOptions) {
    return this.request<{ success: boolean; id: string; status: string }>('/api/v1/crawl', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async map(options: MapOptions) {
    return this.request<{ success: boolean; links: string[]; total: number }>('/api/v1/map', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  async extract(options: ExtractOptions) {
    return this.request<{ success: boolean; data: any }>('/api/v1/extract', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }

  // Keys Management
  keys = {
    list: async () => {
      return this.request<{ success: boolean; keys: any[] }>('/api/v1/keys', {
        method: 'GET',
      });
    },
    create: async (name: string) => {
      return this.request<{ success: boolean; key: any }>('/api/v1/keys', {
        method: 'POST',
        body: JSON.stringify({ name }),
      });
    },
    delete: async (id: string) => {
      return this.request<{ success: boolean; message: string }>(`/api/v1/keys?id=${id}`, {
        method: 'DELETE',
      });
    },
  };

  // Usage & Stats
  async getUsage() {
    return this.request<{
      success: boolean;
      creditsUsedThisMonth: number;
      creditsTotal: number;
      recentRequests: any[];
    }>('/api/v1/usage', {
      method: 'GET',
    });
  }

  // Contact Inquiries
  async submitInquiry(options: ContactOptions) {
    return this.request<{ success: boolean; message: string; inquiryId: string }>('/api/v1/contact', {
      method: 'POST',
      body: JSON.stringify(options),
    });
  }
}
