import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cloned Website",
  description: "Generated by Website Cloner Plugin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
