// <auto-generated>
// Cloned WebApp API Services — C# / .NET Client SDK
// Auto-generated by AGY Website Cloner Plugin
// Version: 1.0.0
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Firecrawl.Client
{
    public class ScrapeOptions
    {
        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        [JsonPropertyName("formats")]
        public List<string>? Formats { get; set; } = new() { "markdown" };

        [JsonPropertyName("onlyMainContent")]
        public bool OnlyMainContent { get; set; } = true;

        [JsonPropertyName("waitFor")]
        public int WaitFor { get; set; } = 0;
    }

    public class CrawlOptions
    {
        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        [JsonPropertyName("limit")]
        public int Limit { get; set; } = 10;

        [JsonPropertyName("maxDepth")]
        public int MaxDepth { get; set; } = 2;
    }

    public class ExtractOptions
    {
        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        [JsonPropertyName("prompt")]
        public string? Prompt { get; set; }

        [JsonPropertyName("schema")]
        public Dictionary<string, object> Schema { get; set; } = new();
    }

    public class ContactOptions
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;

        [JsonPropertyName("email")]
        public string Email { get; set; } = string.Empty;

        [JsonPropertyName("subject")]
        public string? Subject { get; set; } = "Inquiry";

        [JsonPropertyName("message")]
        public string Message { get; set; } = string.Empty;
    }

    public class ApiResponse<T>
    {
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        [JsonPropertyName("data")]
        public T? Data { get; set; }

        [JsonPropertyName("error")]
        public string? Error { get; set; }
    }

    public class FirecrawlClient : IDisposable
    {
        private readonly HttpClient _httpClient;
        private readonly bool _disposeClient;

        public FirecrawlClient(string baseUrl = "http://localhost:3000", string? apiKey = null, HttpClient? httpClient = null)
        {
            _disposeClient = httpClient == null;
            _httpClient = httpClient ?? new HttpClient { BaseAddress = new Uri(baseUrl.TrimEnd('/')) };

            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            if (!string.IsNullOrEmpty(apiKey))
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
            }
        }

        private async Task<T> SendJsonAsync<T>(HttpMethod method, string path, object? body = null, CancellationToken cancellationToken = default)
        {
            using var request = new HttpRequestMessage(method, path);

            if (body != null)
            {
                var json = JsonSerializer.Serialize(body);
                request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            }

            using var response = await _httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);
            var content = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                throw new HttpRequestException($"API request failed with status {response.StatusCode}: {content}");
            }

            return JsonSerializer.Deserialize<T>(content, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;
        }

        public Task<ApiResponse<JsonElement>> ScrapeAsync(ScrapeOptions options, CancellationToken ct = default)
            => SendJsonAsync<ApiResponse<JsonElement>>(HttpMethod.Post, "/api/v1/scrape", options, ct);

        public Task<JsonElement> CrawlAsync(CrawlOptions options, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/crawl", options, ct);

        public Task<JsonElement> MapAsync(string url, int limit = 100, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/map", new { url, limit }, ct);

        public Task<JsonElement> ExtractAsync(ExtractOptions options, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/extract", options, ct);

        public Task<JsonElement> ListKeysAsync(string? workspaceId = null, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Get, $"/api/v1/keys{(workspaceId != null ? $"?workspaceId={workspaceId}" : "")}", null, ct);

        public Task<JsonElement> CreateKeyAsync(string name, string? workspaceId = null, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/keys", new { name, workspaceId }, ct);

        public Task<JsonElement> DeleteKeyAsync(string keyId, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Delete, $"/api/v1/keys?id={keyId}", null, ct);

        public Task<JsonElement> GetUsageAsync(string? workspaceId = null, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Get, $"/api/v1/usage{(workspaceId != null ? $"?workspaceId={workspaceId}" : "")}", null, ct);

        public Task<JsonElement> SubmitInquiryAsync(ContactOptions options, CancellationToken ct = default)
            => SendJsonAsync<JsonElement>(HttpMethod.Post, "/api/v1/contact", options, ct);

        public void Dispose()
        {
            if (_disposeClient)
            {
                _httpClient.Dispose();
            }
        }
    }
}
