"""
Cloned WebApp API Services — Python Client SDK
Auto-generated by AGY Website Cloner Plugin
Version: 1.0.0
"""

import json
import urllib.request
import urllib.error
from typing import Dict, Any, List, Optional

class FirecrawlAppClient:
    def __init__(self, base_url: str = "http://localhost:3000", api_key: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key

    def _request(self, method: str, path: str, data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        url = f"{self.base_url}{path}"
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        body_bytes = json.dumps(data).encode("utf-8") if data else None
        req = urllib.request.Request(url, data=body_bytes, headers=headers, method=method)

        try:
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            error_text = e.read().decode("utf-8")
            raise RuntimeError(f"HTTP {e.code}: {error_text}")

    def scrape(self, url: str, formats: Optional[List[str]] = None, only_main_content: bool = True) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/scrape", {
            "url": url,
            "formats": formats or ["markdown"],
            "onlyMainContent": only_main_content,
        })

    def crawl(self, url: str, limit: int = 10, max_depth: int = 2) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/crawl", {
            "url": url,
            "limit": limit,
            "maxDepth": max_depth,
        })

    def map(self, url: str, search: Optional[str] = None, limit: int = 100) -> Dict[str, Any]:
        payload: Dict[str, Any] = {"url": url, "limit": limit}
        if search:
            payload["search"] = search
        return self._request("POST", "/api/v1/map", payload)

    def extract(self, url: str, schema: Dict[str, Any], prompt: Optional[str] = None) -> Dict[str, Any]:
        payload: Dict[str, Any] = {"url": url, "schema": schema}
        if prompt:
            payload["prompt"] = prompt
        return self._request("POST", "/api/v1/extract", payload)

    def list_keys(self, workspace_id: Optional[str] = None) -> Dict[str, Any]:
        qs = f"?workspaceId={workspace_id}" if workspace_id else ""
        return self._request("GET", f"/api/v1/keys{qs}")

    def create_key(self, name: str, workspace_id: Optional[str] = None) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/keys", {"name": name, "workspaceId": workspace_id})

    def delete_key(self, key_id: str) -> Dict[str, Any]:
        return self._request("DELETE", f"/api/v1/keys?id={key_id}")

    def get_usage(self, workspace_id: Optional[str] = None) -> Dict[str, Any]:
        qs = f"?workspaceId={workspace_id}" if workspace_id else ""
        return self._request("GET", f"/api/v1/usage{qs}")

    def submit_inquiry(self, name: str, email: str, message: str, subject: Optional[str] = None) -> Dict[str, Any]:
        return self._request("POST", "/api/v1/contact", {
            "name": name,
            "email": email,
            "subject": subject or "Inquiry",
            "message": message,
        })
